### ISSUE TITLE
blurry frame removal

### ISSUE THREAD

**Issue by paulwrodriguez** [ProjectIRoniC/OpenPointMesh#4]
_As a user I would like the ability to mark blurry frames,
so that the final point cloud output is more accurate._

_As a developer I should be provided with a list of frames to ignore for a specific .oni file,
so that I can ignore/remove blurry frames from any point clouds constructed for said .oni file._
## Required functionality:
- Frame number capture
- Playback controls including: Pause, Play, Stop, Rewind, Forward
- Means to signal the start of blurry frames to be ignored/removed in the final point cloud
- Means to signal the end of blurry frames to be ignored/removed in the final point cloud
### Tasks:
- [x] Research potential base viewers
- [x] Select base viewer and determine what needs to be added for our solution
- [x] Implement frame capture
- [ ] Store current frame on a given key press
- [x] Implement Pause
- [ ] Implement Play
- [ ] Implement Stop
- [ ] Implement Rewind
- [ ] Implement Forward
- [ ] Implement Start blurry frame
- [ ] Implement Stop blurry frame

**Comment by paulwrodriguez** [comment]
@davchrand this means you

**Comment by nicole-cranon** [comment]
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/tools/openni2_viewer.cpp

This viewer is based off openni2, and already has key press and mouse detection and so a good place to start.
